import { convertHouseType, convertMonthName, convertState } from "../../utils/converts";

type FullModelProps = {
    data: {
      locatorName: string | undefined;
      locatorCpf: string | undefined;
      locatorAddress: string | undefined;
      tenantName: string | undefined;
      tenantCpf: string | undefined;
      tenantRg: string | undefined;
      houseStreet: string | undefined;
      houseNumber: string | undefined;
      houseNeighborhood: string | undefined;
      houseCity: string | undefined;
      houseCep: string | undefined;
      houseState: string;
      houseType: string;
      housePayment: string | undefined;
      housePaymentDay: number | undefined;
      startLocationDate: string | undefined;
      endLocationDate: string | undefined;
      locationTimeMonth: number | undefined;
    };
};

const fullModelHtml = ({data}: FullModelProps) => {
    return `<html>
    <!-- Created by Leoni Melo (https://github.com/leonimeloo) -->
    <!-- Generated by Microsoft Word -->
  <head>
  <meta http-equiv=Content-Type content="text/html; charset=utf-8">
  <meta name=Generator content="leonimeloo">
  <style>
  <!--
   /* Font Definitions */
   @font-face
    {font-family:"Cambria Math";
    panose-1:2 4 5 3 5 4 6 3 2 4;
    mso-font-charset:0;
    mso-generic-font-family:roman;
    mso-font-pitch:variable;
    mso-font-signature:3 0 0 0 1 0;}
  @font-face
    {font-family:Calibri;
    panose-1:2 15 5 2 2 2 4 3 2 4;
    mso-font-charset:0;
    mso-generic-font-family:swiss;
    mso-font-pitch:variable;
    mso-font-signature:-469750017 -1073732485 9 0 511 0;}
   /* Style Definitions */
   p.MsoNormal, li.MsoNormal, div.MsoNormal
    {mso-style-unhide:no;
    mso-style-qformat:yes;
    mso-style-parent:"";
    margin-top:0cm;
    margin-right:0cm;
    margin-bottom:.15pt;
    margin-left:72.55pt;
    text-indent:-.5pt;
    line-height:106%;
    mso-pagination:widow-orphan;
    font-size:11.0pt;
    font-family:"Arial",sans-serif;
    mso-fareast-font-family:Arial;
    color:black;}
  h1
    {mso-style-priority:9;
    mso-style-unhide:no;
    mso-style-qformat:yes;
    mso-style-parent:"";
    mso-style-link:"Título 1 Char";
    mso-style-next:Normal;
    margin-top:0cm;
    margin-right:0cm;
    margin-bottom:0cm;
    margin-left:36.5pt;
    text-indent:-.5pt;
    line-height:107%;
    mso-pagination:widow-orphan lines-together;
    page-break-after:avoid;
    mso-outline-level:1;
    font-size:11.0pt;
    font-family:"Arial",sans-serif;
    mso-fareast-font-family:Arial;
    color:black;
    mso-font-kerning:0pt;
    mso-bidi-font-weight:normal;
    text-underline:black;
    text-decoration:underline;
    text-underline:single;}
  span.Ttulo1Char
    {mso-style-name:"Título 1 Char";
    mso-style-unhide:no;
    mso-style-locked:yes;
    mso-style-parent:"";
    mso-style-link:"Título 1";
    mso-ansi-font-size:11.0pt;
    font-family:"Arial",sans-serif;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    font-weight:bold;
    mso-bidi-font-weight:normal;
    text-underline:black;
    text-decoration:underline;
    text-underline:single;}
  .MsoChpDefault
    {mso-style-type:export-only;
    mso-default-props:yes;
    font-family:"Calibri",sans-serif;
    mso-ascii-font-family:Calibri;
    mso-ascii-theme-font:minor-latin;
    mso-fareast-font-family:"Times New Roman";
    mso-fareast-theme-font:minor-fareast;
    mso-hansi-font-family:Calibri;
    mso-hansi-theme-font:minor-latin;
    mso-bidi-font-family:"Times New Roman";
    mso-bidi-theme-font:minor-bidi;}
  .MsoPapDefault
    {mso-style-type:export-only;
    margin-bottom:8.0pt;
    line-height:107%;}
  @page WordSection1
    {size:612.0pt 792.0pt;
    margin:71.2pt 84.7pt 80.1pt 85.0pt;
    mso-header-margin:36.0pt;
    mso-footer-margin:36.0pt;
    mso-paper-source:0;}
  div.WordSection1
    {page:WordSection1;}
   /* List Definitions */
   @list l0
    {mso-list-id:999574767;
    mso-list-template-ids:1364727966;}
  @list l0:level1
    {mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:35.25pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level2
    {mso-level-text:"%1\.%2\.";
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:108.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level3
    {mso-level-number-format:roman-lower;
    mso-level-text:%3;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:126.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level4
    {mso-level-text:%4;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:162.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level5
    {mso-level-number-format:alpha-lower;
    mso-level-text:%5;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:198.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level6
    {mso-level-number-format:roman-lower;
    mso-level-text:%6;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:234.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level7
    {mso-level-text:%7;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:270.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level8
    {mso-level-number-format:alpha-lower;
    mso-level-text:%8;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:306.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  @list l0:level9
    {mso-level-number-format:roman-lower;
    mso-level-text:%9;
    mso-level-tab-stop:none;
    mso-level-number-position:left;
    margin-left:342.05pt;
    text-indent:0cm;
    mso-ansi-font-size:11.0pt;
    mso-bidi-font-size:11.0pt;
    mso-ascii-font-family:Arial;
    mso-fareast-font-family:Arial;
    mso-hansi-font-family:Arial;
    mso-bidi-font-family:Arial;
    color:black;
    border:none;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;
    mso-ansi-font-style:normal;
    text-underline:black;
    text-decoration:none;
    text-underline:none;
    text-decoration:none;
    text-line-through:none;
    vertical-align:baseline;}
  ol
    {margin-bottom:0cm;}
  ul
    {margin-bottom:0cm;}
  -->
  </style>
  <!--[if gte mso 10]>
  <style>
   /* Style Definitions */
   table.MsoNormalTable
    {mso-style-name:"Tabela normal";
    mso-tstyle-rowband-size:0;
    mso-tstyle-colband-size:0;
    mso-style-noshow:yes;
    mso-style-priority:99;
    mso-style-parent:"";
    mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
    mso-para-margin-top:0cm;
    mso-para-margin-right:0cm;
    mso-para-margin-bottom:8.0pt;
    mso-para-margin-left:0cm;
    line-height:107%;
    mso-pagination:widow-orphan;
    font-size:11.0pt;
    font-family:"Calibri",sans-serif;
    mso-ascii-font-family:Calibri;
    mso-ascii-theme-font:minor-latin;
    mso-hansi-font-family:Calibri;
    mso-hansi-theme-font:minor-latin;
    mso-bidi-font-family:"Times New Roman";
    mso-bidi-theme-font:minor-bidi;}
  </style>
  <![endif]--><!--[if gte mso 9]><xml>
   <o:shapedefaults v:ext="edit" spidmax="1030"/>
  </xml><![endif]--><!--[if gte mso 9]><xml>
   <o:shapelayout v:ext="edit">
    <o:idmap v:ext="edit" data="1"/>
   </o:shapelayout></xml><![endif]-->
  </head>
  
  <body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>
  
  <div class=WordSection1>
  
  <p class=MsoNormal align=center style='margin-top:0cm;margin-right:.9pt;
  margin-bottom:5.25pt;margin-left:0cm;text-align:center;text-indent:0cm;
  line-height:107%'><b style='mso-bidi-font-weight:normal'><span
  style='font-size:14.0pt;mso-bidi-font-size:11.0pt;line-height:107%'>INSTRUMENTO
  CONTRATUAL DE LOCAÇÃO </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:0cm;text-indent:0cm;line-height:107%'><span
  style='mso-spacerun:yes'> </span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:35.25pt;text-indent:-18.0pt;line-height:107%;mso-list:l0 level1 lfo1'><![if !supportLists]><b><span
  style='mso-list:Ignore'>1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;
  </span></span></b><![endif]><b style='mso-bidi-font-weight:normal'>DAS PARTES </b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span
  style='mso-spacerun:yes'> </span></p>
  
  <p class=MsoNormal style='margin-left:108.05pt;text-indent:-36.0pt;mso-list:
  l0 level2 lfo1'><![if !supportLists]><b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><span style='mso-list:Ignore'>1.1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </span></span></span></b><![endif]><b style='mso-bidi-font-weight:normal'><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>LOCADOR</span></b><span lang=PT-BR
  style='mso-ansi-language:PT-BR'>: <b style='mso-bidi-font-weight:normal'><u
  style='text-underline:black'>${data.locatorName}</u></b>,
  brasileiro(a), inscrito no CPF n° ${data.locatorCpf}, com endereço em ${data.locatorAddress}; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:108.05pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:108.05pt;text-indent:-36.0pt;mso-list:
  l0 level2 lfo1'><![if !supportLists]><b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><span style='mso-list:Ignore'>1.2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </span></span></span></b><![endif]><b style='mso-bidi-font-weight:normal'><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>LOCATÁRIO</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>: <b style='mso-bidi-font-weight:
  normal'><u style="text-decoration: underline;">${data.tenantName}</u></b>, brasileiro(a), portador do RG n°
  ${data.tenantRg} e CPF nº ${data.tenantCpf}, residente e domiciliado(a) à ${data.houseStreet}, n° ${data.houseNumber} - ${data.houseNeighborhood}, CEP n° ${data.houseCep}, no município de ${data.houseCity}, ${convertState(data.houseState)}. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:35.25pt;text-indent:-18.0pt;line-height:107%;mso-list:l0 level1 lfo1'><![if !supportLists]><b><span
  style='mso-list:Ignore'>2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;
  </span></span></b><![endif]><b style='mso-bidi-font-weight:normal'>DAS
  CLÁUSULAS </b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <h1 style='margin-left:35.75pt'>DA FINALIDADE<span style='text-decoration:none;
  text-underline:none'> </span></h1>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.1 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>A presente locação tem como
  finalidade exercício da posse sobre o imóvel de maneira<b style='mso-bidi-font-weight:
  normal'> ${convertHouseType(data.houseType)}</b>. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <h1 style='margin-left:35.75pt'><span lang=PT-BR style='mso-ansi-language:PT-BR'>DO
  PRAZO</span><span lang=PT-BR style='mso-ansi-language:PT-BR;text-decoration:
  none;text-underline:none'> </span><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></h1>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.2 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>O prazo de locação é de ${data.locationTimeMonth}
  meses, iniciando-se em ${data.startLocationDate} e terminando em ${data.endLocationDate}, podendo, por
  deliberação das partes, <b style='mso-bidi-font-weight:normal'>LOCADOR</b> e <b
  style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>, ser prorrogado por mais 24
  (vinte e quatro) meses, quando então será considerada finda, independentemente
  de notificação judicial ou extrajudicial, obrigando-se o <b style='mso-bidi-font-weight:
  normal'>LOCATÁRIO</b> a restituir o imóvel, completamente livre e desocupado de
  pessoas e coisas, e em perfeito estado de uso e conservação; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.2.1 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>Durante o prazo estipulado para a
  duração do contrato, o <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>
  poderá desocupar, devolver o imóvel, ficando, porém, liberado da multa
  contratual após 6 (seis) meses de locação. Tal benefício estende-se também o <b
  style='mso-bidi-font-weight:normal'>LOCADOR</b>, ressaltando-se que, ambos
  deverão comunicar por escrito com 30 (trinta) dias de antecedência a
  necessidade de desocupação do imóvel. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <h1 style='margin-left:35.75pt'><span lang=PT-BR style='mso-ansi-language:PT-BR'>DO
  ALUGUEL, ENCARGOS E REAJUSTE</span><span lang=PT-BR style='mso-ansi-language:
  PT-BR;text-decoration:none;text-underline:none'> </span><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><o:p></o:p></span></h1>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.3</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> Fica ajustado o valor mensal de <b
  style='mso-bidi-font-weight:normal'>${data.housePayment}</b> como remuneração para a presente locação. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:.1pt;
  margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.3.2</span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'> O
  pagamento do aluguel deverá ser realizado pontualmente todo dia <b
  style='mso-bidi-font-weight:normal'>${data.housePaymentDay} de cada mês</b>, durante o período
  locatício, mediante transferência bancária ou pix, de
  titularidade de ${data.locatorName}, portador do CPF nº
  ${data.locatorCpf}; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:10.9pt;margin-bottom:
  .1pt;margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.3.3 </span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'>Se
  houver atraso ao pagamento descrito acima, o valor mensal do aluguel sofrerá
  acréscimo de multa de 10% (dez por cento), acrescido de juros de 0,33% (zero
  vírgula trinta e três por cento) ao dia de atraso, até seu adimplemento; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.3.4</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> O reajuste do valor do aluguel será
  anual, pelo indexador IGP-M da Fundação Getúlio Vargas, acumulados no período,
  e no caso de sua extinção, de forma alternativa e subsidiária, pelos do IGP-DI
  ou INPC, incidindo na presente locação a partir de ${convertMonthName(new Date().getMonth() + 1)} de ${new Date().getFullYear()}; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.3.5</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> Ficará sob responsabilidade e
  adimplemento do <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b> todos os
  impostos, taxas ou contas de consumo que recaiam ou venham a recair sobre o
  imóvel locado, bem como qualquer aumento dos mesmos, ou novos que venham a ser
  criados pelo Poder Público; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:.1pt;
  margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.3.5</span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'> Ficará
  sob responsabilidade do <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>
  pagar multa rescisória do valor de <b style='mso-bidi-font-weight:normal'>R$
  600,00 (seiscentos reais)</b> caso deseje terminar o contrato antes do tempo
  previsto. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <h1 style='margin-left:35.75pt'><span lang=PT-BR style='mso-ansi-language:PT-BR'>DO
  ESTADO, CONSERVAÇÃO E USO DO IMÓVEL</span><span lang=PT-BR style='mso-ansi-language:
  PT-BR;text-decoration:none;text-underline:none'> </span><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><o:p></o:p></span></h1>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.4</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> O imóvel objeto deste instrumento é
  locado exclusivamente para servir de fins residenciais ao <b style='mso-bidi-font-weight:
  normal'>LOCATÁRIO</b>, não podendo sua destinação ser alterada, substituída ou
  acrescida de qualquer outra, sem prévia e expressa anuência do <b
  style='mso-bidi-font-weight:normal'>LOCADOR</b>. Fica vedado, outrossim, a
  sublocação, cessão ou transferência deste contrato, bem como o empréstimo,
  parcial ou total do imóvel locado, que dependerão também, de prévia e expressa
  anuência do <b style='mso-bidi-font-weight:normal'>LOCADOR</b>; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.4.1</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> Constatadas eventuais
  irregularidades e a necessidade de reparos no imóvel em decorrência de uso
  indevido, fará o <b style='mso-bidi-font-weight:normal'>LOCADOR</b> apresentar
  de imediato ao <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>, um
  orçamento prévio assinado por profissional do ramo, sendo-lhe facilitado pagar
  o valor nele declinado, liberando-se assim de eventuais ônus em razão de demora
  e/ou imperfeições nos serviços. Caso contrário, poderá este segundo, contratar
  por sua própria conta e risco, mão de obra especializada, arcando nessa
  condição com os riscos de eventuais imperfeições dos serviços e pelo pagamento
  do aluguel dos dias despendidos para a sua execução; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.4.2</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> No prazo de 10 (dez) dias, a contar
  do início da locação, poderá o <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>
  reclamar por escrito ao <b style='mso-bidi-font-weight:normal'>LOCADOR</b>,
  eventual defeito ou comprometimento de</span><span lang=PT-BR style='font-family:
  "Calibri",sans-serif;mso-fareast-font-family:Calibri;mso-ansi-language:PT-BR'> </span><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>equipamentos ou peças constantes no
  imóvel locado, bem como pequenos reparos imperceptíveis na época da vistoria.
  Uma vez decorrido o referido prazo sem a comunicação, as responsabilidades
  passam apenas ao <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>LOCATÁRIO</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>, correndo por sua conta em risco;<b
  style='mso-bidi-font-weight:normal'> </b><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:10.3pt;margin-bottom:
  .1pt;margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.4.3</span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'>
  Quaisquer modificações não autorizadas deverão ser desfeitas, restituindo-se o
  imóvel no estado anterior, a expensas do <b style='mso-bidi-font-weight:normal'>LOCATÁRIO</b>,
  sem prejuízo da incidência de multa; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:.1pt;
  margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.4.4 </span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'>O <b
  style='mso-bidi-font-weight:normal'>LOCATÁRIO</b> não pode realizar
  modificações internas ou externas no imóvel sem consentimento prévio e expresso
  do <b style='mso-bidi-font-weight:normal'>LOCADOR</b>, sob pena de rescisão do
  presente Contrato; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.4.5</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> As deteriorações estranhas ao uso
  normal do Imóvel poderão ensejar a rescisão da avença locatícia e o <b
  style='mso-bidi-font-weight:normal'>LOCATÁRIO</b> não se exime do dever de
  indenizar o reparo dos estragos a que der causa, mediante o pagamento da multa
  de que se trata a cláusula 3.5., a título de indenização de lucro cessante; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.4.7</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> Fica o <b style='mso-bidi-font-weight:
  normal'>LOCATÁRIO</b> obrigado a satisfazer todas as exigências dos poderes
  públicos, observando quanto às atividades desenvolvidas no prédio, o regimento
  interno e todas as disposições legais pertinentes. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <h1 style='margin-left:35.75pt'><span lang=PT-BR style='mso-ansi-language:PT-BR'>OUTRAS
  DISPOSIÇÕES</span><span lang=PT-BR style='mso-ansi-language:PT-BR;text-decoration:
  none;text-underline:none'> </span><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></h1>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'><span
  style='mso-spacerun:yes'> </span></span></b><span lang=PT-BR style='mso-ansi-language:
  PT-BR'><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5 LOCADOR</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> e <b style='mso-bidi-font-weight:
  normal'>LOCATÁRIO</b> obrigam-se a respeitar o presente contrato tal qual
  redigido, incorrendo ao constante que infringir qualquer cláusula aqui
  estipuladas, uma multa correspondente ao valor de 03 (três) aluguéis constantes
  em cláusula <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'>3.3., caput, independente de qualquer
  interpelação; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5.1 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>Fica o <b style='mso-bidi-font-weight:
  normal'>LOCADOR</b>, por si ou por seus prepostos, autorizado a vistoriar o
  imóvel sempre que julgar conveniente mediante prévio agendamento; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5.2 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>Desocupado o imóvel, o <b
  style='mso-bidi-font-weight:normal'>LOCATÁRIO</b> se obriga no ato da entrega
  das chaves a exibir os comprovantes de pagamentos das contas de consumo do
  imóvel, até a data da desocupação, ou oferecer, à título de caução, quantia
  correspondente ao último pagamento efetuado para adimplir as contas de consumo;
  <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5.3</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> O <b style='mso-bidi-font-weight:
  normal'>LOCADOR</b> vistoriou e fotografou o imóvel objeto da presente locação,
  do qual será oportunamente assinado pelas partes; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:7.1pt;margin-bottom:.1pt;
  margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.5.4</span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'> Tudo
  quanto for devido em razão do presente Contrato, se não for pago nos
  respectivos vencimentos, será cobrado em ação judicial, respondendo o <b
  style='mso-bidi-font-weight:normal'>LOCATÁRIO</b> pelo pagamento do 20% (vinte
  por cento) do valor da causa a título de honorários advocatícios; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:8.55pt;margin-bottom:
  .1pt;margin-left:35.75pt;text-align:justify;text-justify:inter-ideograph'><b
  style='mso-bidi-font-weight:normal'><span lang=PT-BR style='mso-ansi-language:
  PT-BR'>3.5.5</span></b><span lang=PT-BR style='mso-ansi-language:PT-BR'> Fica
  ainda acordado entre as partes que em caso de atraso de pagamento da prestação
  locatícia por prazo igual ou superior a 15 (quinze) dias, fica o <b
  style='mso-bidi-font-weight:normal'>LOCADOR</b> autorizado a enviar cobrança
  extrajudicial, bem como inscrição do débito nos portais de proteção ao crédito,
  sendo certo que, o valor será acrescido de multa e honorários advocatícios; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5.6</span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'> O disposto neste Contrato, em todas
  as cláusulas, só poderá ser alterado por escrito, não se admitindo, em caso
  algum, alteração verbal; <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-left:35.75pt'><b style='mso-bidi-font-weight:
  normal'><span lang=PT-BR style='mso-ansi-language:PT-BR'>3.5.7 </span></b><span
  lang=PT-BR style='mso-ansi-language:PT-BR'>Todas as disposições da presente
  locação estão sujeitas a observação e aplicabilidade da Lei de Locações de
  Imóveis Urbanos (Lei n° 8.245/91). <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-bottom:.1pt;text-align:justify;text-justify:
  inter-ideograph'><span lang=PT-BR style='mso-ansi-language:PT-BR'>Por estarem
  assim justas e contratadas, assinam o presente, em 02 (duas) vias, cada qual
  com 04 (quatro) laudas de igual teor e forma, para que surta seus legais e
  jurídicos efeitos, obrigando-se por si, seus herdeiros e/ou sucessores, ao fiel
  cumprimento de todas as cláusulas e condições. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:72.05pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:72.05pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal align=right style='margin-top:0cm;margin-right:.1pt;
  margin-bottom:0cm;margin-left:0cm;text-align:right;text-indent:0cm;line-height:
  107%'><span lang=PT-BR style='mso-ansi-language:PT-BR'>${data.houseCity}, ${convertState(data.houseState)}, ${new Date().getDate()} de ${convertMonthName(new Date().getMonth() + 1)} de ${new Date().getFullYear()}. <o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:72.05pt;text-indent:0cm;line-height:107%'><span lang=PT-BR
  style='mso-ansi-language:PT-BR'><span style='mso-spacerun:yes'> </span><o:p></o:p></span></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.5pt;line-height:107%'><b style='mso-bidi-font-weight:normal'>LOCADOR:
  </b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:8.1pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:8.1pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span><span style='mso-tab-count:1'>           </span><span
  style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:8.15pt;
  margin-left:0cm;text-indent:0cm;line-height:107%;tab-stops:center 36.0pt right 442.3pt'><span
  style='font-family:"Calibri",sans-serif;mso-fareast-font-family:Calibri'><span
  style='mso-tab-count:1'>                </span></span><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span><span style='mso-tab-count:1'>       </span></b><!--[if mso & !supportInlineShapes & supportFields]><span
  style='mso-element:field-begin;mso-field-lock:yes'></span><span
  style='mso-spacerun:yes'> </span>SHAPE <span
  style='mso-spacerun:yes'> </span>\* MERGEFORMAT <span style='mso-element:field-separator'></span><![endif]--><!--[if gte vml 1]><v:group
   id="Group_x0020_4452" o:spid="_x0000_s1028" style='width:381.75pt;height:.75pt;
   mso-position-horizontal-relative:char;mso-position-vertical-relative:line'
   coordsize="48482,95" o:gfxdata="UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF
  90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA
  0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD
  OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893
  SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y
  JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl
  bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR
  JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY
  22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i
  OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA
  IQBiHK/HUgIAALoFAAAOAAAAZHJzL2Uyb0RvYy54bWykVMtu2zAQvBfoPxC815KFOHEEyzk0rS9F
  GzTpB9AUKQngCyRt2X/f5VqWVQfNIfFBXom7w9nZx+rhoBXZCx86ayo6n+WUCMNt3Zmmon9evn9Z
  UhIiMzVT1oiKHkWgD+vPn1a9K0VhW6tq4QmAmFD2rqJtjK7MssBboVmYWScMHErrNYvw6pus9qwH
  dK2yIs9vs9762nnLRQjw9fF0SNeIL6Xg8ZeUQUSiKgrcIj49Prfpma1XrGw8c23HBxrsHSw06wxc
  OkI9ssjIznevoHTHvQ1Wxhm3OrNSdlxgDpDNPL/KZuPtzmEuTdk3bpQJpL3S6d2w/Od+492ze/Kg
  RO8a0ALfUi4H6XX6B5bkgJIdR8nEIRIOH2+WN8uiWFDC4ex+ARYqyluQ/VUQb7+9FZadr8z+IdI7
  aI1wyT58LPvnljmBooYSsn/ypKsrentXUGKYhhZFB5I+oCToNQoUygBafUidMU1W8l2IG2FRZbb/
  EeKpHeuzxdqzxQ/mbHpo6jfb2bGY4hLJZJJ+UqZ2qFI61HYvXiy6xataAcfLqTJTr7Hik4KD+8kJ
  jHTlejUYSAPsaaLKJEbz+3wBA8kZDL1ULOL06C7CNlCdhvPiLs9xPhEcEFMfnMRHKx6VSNyV+S0k
  1BCacY4gwTfbr8qTPUszj79USYQB1xQjO6XGqPy/UcmVKdeyAWuAGS5AyAEpeQpcN9ewfGBz2jkw
  uZD0efMApTEIaVkTx3gD+xIvnGSbzK2tjzitKAgMBkqDCwIZDcssbaDpO3pdVu76LwAAAP//AwBQ
  SwMEFAAGAAgAAAAhAP3f5mzbAAAAAwEAAA8AAABkcnMvZG93bnJldi54bWxMj0FLw0AQhe+C/2EZ
  wZvdxJJaYjalFPVUBFtBepsm0yQ0Oxuy2yT9945e9PJgeI/3vslWk23VQL1vHBuIZxEo4sKVDVcG
  PvevD0tQPiCX2DomA1fysMpvbzJMSzfyBw27UCkpYZ+igTqELtXaFzVZ9DPXEYt3cr3FIGdf6bLH
  Ucptqx+jaKEtNiwLNXa0qak47y7WwNuI43oevwzb82lzPeyT969tTMbc303rZ1CBpvAXhh98QYdc
  mI7uwqVXrQF5JPyqeE+LeQLqKKEEdJ7p/+z5NwAAAP//AwBQSwECLQAUAAYACAAAACEAtoM4kv4A
  AADhAQAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAA
  IQA4/SH/1gAAAJQBAAALAAAAAAAAAAAAAAAAAC8BAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAA
  IQBiHK/HUgIAALoFAAAOAAAAAAAAAAAAAAAAAC4CAABkcnMvZTJvRG9jLnhtbFBLAQItABQABgAI
  AAAAIQD93+Zs2wAAAAMBAAAPAAAAAAAAAAAAAAAAAKwEAABkcnMvZG93bnJldi54bWxQSwUGAAAA
  AAQABADzAAAAtAUAAAAA
  ">
   <v:shape id="Shape_x0020_672" o:spid="_x0000_s1029" style='position:absolute;
    width:48482;height:95;visibility:visible;mso-wrap-style:square;
    v-text-anchor:top' coordsize="4848225,9525" o:gfxdata="UEsDBBQABgAIAAAAIQDb4fbL7gAAAIUBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbHyQz07DMAyH
  70i8Q+QralM4IITa7kDhCAiNB7ASt43WOlEcyvb2pNu4IODoPz9/n1xv9vOkForiPDdwXVagiI23
  jocG3rdPxR0oScgWJ8/UwIEENu3lRb09BBKV0ywNjCmFe63FjDSjlD4Q50nv44wpl3HQAc0OB9I3
  VXWrjedEnIq03oC27qjHjympx31un0wiTQLq4bS4shrAECZnMGVTvbD9QSnOhDInjzsyuiBXWQP0
  r4R18jfgnHvJr4nOknrFmJ5xzhraRtHWf3Kkpfz/yGo5S+H73hkquyhdjr3R8m2lj09svwAAAP//
  AwBQSwMEFAAGAAgAAAAhAFr0LFu/AAAAFQEAAAsAAABfcmVscy8ucmVsc2zPwWrDMAwG4Ptg72B0
  X5TuUMaI01uh19I+gLGVxCy2jGSy9e1nemrHjpL4P0nD4SetZiPRyNnCruvBUPYcYp4tXC/Htw8w
  Wl0ObuVMFm6kcBhfX4Yzra62kC6xqGlKVgtLreUTUf1CyWnHhXKbTCzJ1VbKjMX5LzcTvvf9HuXR
  gPHJNKdgQU5hB+ZyK23zHztFL6w81c5zQp6m6P9TMfB3PtPWFCczVQtB9N4U2rp2HOA44NMz4y8A
  AAD//wMAUEsDBBQABgAIAAAAIQC+RQpWwwAAANwAAAAPAAAAZHJzL2Rvd25yZXYueG1sRI/BbsIw
  EETvlfgHa5F6K3Y4QBUwqEIguBLKgdsSb5O08dqKTQh/X1eqxHE0M280y/VgW9FTFxrHGrKJAkFc
  OtNwpeHztHt7BxEissHWMWl4UID1avSyxNy4Ox+pL2IlEoRDjhrqGH0uZShrshgmzhMn78t1FmOS
  XSVNh/cEt62cKjWTFhtOCzV62tRU/hQ3q+FSbNXl7B+Zymj/3bfyevRqrvXrePhYgIg0xGf4v30w
  GmbzKfydSUdArn4BAAD//wMAUEsBAi0AFAAGAAgAAAAhANvh9svuAAAAhQEAABMAAAAAAAAAAAAA
  AAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAWvQsW78AAAAVAQAACwAA
  AAAAAAAAAAAAAAAfAQAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEAvkUKVsMAAADcAAAADwAA
  AAAAAAAAAAAAAAAHAgAAZHJzL2Rvd25yZXYueG1sUEsFBgAAAAADAAMAtwAAAPcCAAAAAA==
  " path="m,l4848225,9525e" filled="f" strokeweight="1.5pt">
    <v:stroke miterlimit="83231f" joinstyle="miter"/>
    <v:path arrowok="t" textboxrect="0,0,4848225,9525"/>
   </v:shape><w:wrap type="none"/>
   <w:anchorlock/>
  </v:group><![endif]--><![if !vml]><img width=512 height=4
  src="template_arquivos/image001.gif" v:shapes="Group_x0020_4452 Shape_x0020_672"><![endif]><!--[if gte vml 1]><v:shapetype
   id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
   path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
   <v:stroke joinstyle="miter"/>
   <v:formulas>
    <v:f eqn="if lineDrawn pixelLineWidth 0"/>
    <v:f eqn="sum @0 1 0"/>
    <v:f eqn="sum 0 0 @1"/>
    <v:f eqn="prod @2 1 2"/>
    <v:f eqn="prod @3 21600 pixelWidth"/>
    <v:f eqn="prod @3 21600 pixelHeight"/>
    <v:f eqn="sum @0 0 1"/>
    <v:f eqn="prod @6 1 2"/>
    <v:f eqn="prod @7 21600 pixelWidth"/>
    <v:f eqn="sum @8 21600 0"/>
    <v:f eqn="prod @7 21600 pixelHeight"/>
    <v:f eqn="sum @10 21600 0"/>
   </v:formulas>
   <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
   <o:lock v:ext="edit" aspectratio="t"/>
  </v:shapetype><![endif]--><!--[if mso & !supportInlineShapes & supportFields]><v:shape
   id="_x0000_i1026" type="#_x0000_t75" style='width:381.75pt;height:.75pt'>
   <v:imagedata croptop="-65520f" cropbottom="65520f"/>
  </v:shape><span style='mso-element:field-end'></span><![endif]--></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:7.75pt;
  margin-left:36.5pt;line-height:107%'><b style='mso-bidi-font-weight:normal'>LOCATÁRIO:
  </b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:8.15pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:17.95pt;
  margin-left:36.0pt;text-indent:0cm;line-height:107%'><b style='mso-bidi-font-weight:
  normal'><span style='mso-spacerun:yes'> </span></b></p>
  
  <p class=MsoNormal style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;
  margin-left:57.95pt;text-indent:0cm;line-height:107%'><!--[if mso & !supportInlineShapes & supportFields]><span
  style='mso-element:field-begin;mso-field-lock:yes'></span><span
  style='mso-spacerun:yes'> </span>SHAPE <span
  style='mso-spacerun:yes'> </span>\* MERGEFORMAT <span style='mso-element:field-separator'></span><![endif]--><!--[if gte vml 1]><v:group
   id="Group_x0020_4453" o:spid="_x0000_s1026" style='width:381.75pt;height:.75pt;
   mso-position-horizontal-relative:char;mso-position-vertical-relative:line'
   coordsize="48482,95" o:gfxdata="UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF
  90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA
  0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD
  OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893
  SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y
  JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl
  bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR
  JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY
  22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i
  OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA
  IQChWnOdUgIAALoFAAAOAAAAZHJzL2Uyb0RvYy54bWykVMlu2zAQvRfoPxC815LdOHEEyzkkrS9F
  G2T5AJoiJQHcQNKW/fcdjmVZddAcEh/kkTjz+ObNsrzba0V2wofWmpJOJzklwnBbtaYu6evLz28L
  SkJkpmLKGlHSgwj0bvX1y7JzhZjZxqpKeAIgJhSdK2kToyuyLPBGaBYm1gkDh9J6zSK8+jqrPOsA
  XatslufXWWd95bzlIgT4+nA8pCvEl1Lw+EfKICJRJQVuEZ8en5v0zFZLVtSeuablPQ32ARaatQYu
  HaAeWGRk69s3ULrl3gYr44RbnVkpWy4wB8hmml9ks/Z26zCXuuhqN8gE0l7o9GFY/nu39u7ZPXpQ
  onM1aIFvKZe99Dr9A0uyR8kOg2RiHwmHj1eLq8VsNqeEw9ntHCxUlDcg+5sg3vx4Lyw7XZn9Q6Rz
  0BrhnH34XPbPDXMCRQ0FZP/oSVuV9PrmOyWGaWhRdCDpA0qCXoNAoQig1afUGdJkBd+GuBYWVWa7
  XyEe27E6Waw5WXxvTqaHpn63nR2LKS6RTCbpRmVq+iqlQ2134sWiW7yoFXA8nyoz9hoqPio4uB+d
  wEhXrpa9gTTAHieqTGI0vc3nMJCcwdBLxSJOj24jbAPVajif3eQ5zieCA2Lqg6P4aMWDEom7Mk9C
  Qg2hGacIEny9uVee7FiaefylSiIMuKYY2So1ROX/jUquTLmG9Vg9TH8BQvZIyVPgurmE5T2b486B
  yYWkT5sHKA1BSMuaOMQb2Jd44SjbZG5sdcBpRUFgMFAaXBDIqF9maQON39HrvHJXfwEAAP//AwBQ
  SwMEFAAGAAgAAAAhAP3f5mzbAAAAAwEAAA8AAABkcnMvZG93bnJldi54bWxMj0FLw0AQhe+C/2EZ
  wZvdxJJaYjalFPVUBFtBepsm0yQ0Oxuy2yT9945e9PJgeI/3vslWk23VQL1vHBuIZxEo4sKVDVcG
  PvevD0tQPiCX2DomA1fysMpvbzJMSzfyBw27UCkpYZ+igTqELtXaFzVZ9DPXEYt3cr3FIGdf6bLH
  Ucptqx+jaKEtNiwLNXa0qak47y7WwNuI43oevwzb82lzPeyT969tTMbc303rZ1CBpvAXhh98QYdc
  mI7uwqVXrQF5JPyqeE+LeQLqKKEEdJ7p/+z5NwAAAP//AwBQSwECLQAUAAYACAAAACEAtoM4kv4A
  AADhAQAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAA
  IQA4/SH/1gAAAJQBAAALAAAAAAAAAAAAAAAAAC8BAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAA
  IQChWnOdUgIAALoFAAAOAAAAAAAAAAAAAAAAAC4CAABkcnMvZTJvRG9jLnhtbFBLAQItABQABgAI
  AAAAIQD93+Zs2wAAAAMBAAAPAAAAAAAAAAAAAAAAAKwEAABkcnMvZG93bnJldi54bWxQSwUGAAAA
  AAQABADzAAAAtAUAAAAA
  ">
   <v:shape id="Shape_x0020_673" o:spid="_x0000_s1027" style='position:absolute;
    width:48482;height:95;visibility:visible;mso-wrap-style:square;
    v-text-anchor:top' coordsize="4848225,9525" o:gfxdata="UEsDBBQABgAIAAAAIQDb4fbL7gAAAIUBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbHyQz07DMAyH
  70i8Q+QralM4IITa7kDhCAiNB7ASt43WOlEcyvb2pNu4IODoPz9/n1xv9vOkForiPDdwXVagiI23
  jocG3rdPxR0oScgWJ8/UwIEENu3lRb09BBKV0ywNjCmFe63FjDSjlD4Q50nv44wpl3HQAc0OB9I3
  VXWrjedEnIq03oC27qjHjympx31un0wiTQLq4bS4shrAECZnMGVTvbD9QSnOhDInjzsyuiBXWQP0
  r4R18jfgnHvJr4nOknrFmJ5xzhraRtHWf3Kkpfz/yGo5S+H73hkquyhdjr3R8m2lj09svwAAAP//
  AwBQSwMEFAAGAAgAAAAhAFr0LFu/AAAAFQEAAAsAAABfcmVscy8ucmVsc2zPwWrDMAwG4Ptg72B0
  X5TuUMaI01uh19I+gLGVxCy2jGSy9e1nemrHjpL4P0nD4SetZiPRyNnCruvBUPYcYp4tXC/Htw8w
  Wl0ObuVMFm6kcBhfX4Yzra62kC6xqGlKVgtLreUTUf1CyWnHhXKbTCzJ1VbKjMX5LzcTvvf9HuXR
  gPHJNKdgQU5hB+ZyK23zHztFL6w81c5zQp6m6P9TMfB3PtPWFCczVQtB9N4U2rp2HOA44NMz4y8A
  AAD//wMAUEsDBBQABgAIAAAAIQDRCa/NwwAAANwAAAAPAAAAZHJzL2Rvd25yZXYueG1sRI9BawIx
  FITvBf9DeEJvNVkLKlujiCj26lYP3l43r7tbNy9hE9f13zeFQo/DzHzDLNeDbUVPXWgca8gmCgRx
  6UzDlYbTx/5lASJEZIOtY9LwoADr1ehpiblxdz5SX8RKJAiHHDXUMfpcylDWZDFMnCdO3pfrLMYk
  u0qaDu8Jbls5VWomLTacFmr0tK2pvBY3q+FS7NTl7B+Zyujw3bfy8+jVXOvn8bB5AxFpiP/hv/a7
  0TCbv8LvmXQE5OoHAAD//wMAUEsBAi0AFAAGAAgAAAAhANvh9svuAAAAhQEAABMAAAAAAAAAAAAA
  AAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAWvQsW78AAAAVAQAACwAA
  AAAAAAAAAAAAAAAfAQAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEA0QmvzcMAAADcAAAADwAA
  AAAAAAAAAAAAAAAHAgAAZHJzL2Rvd25yZXYueG1sUEsFBgAAAAADAAMAtwAAAPcCAAAAAA==
  " path="m,l4848225,9525e" filled="f" strokeweight="1.5pt">
    <v:stroke miterlimit="83231f" joinstyle="miter"/>
    <v:path arrowok="t" textboxrect="0,0,4848225,9525"/>
   </v:shape><w:wrap type="none"/>
   <w:anchorlock/>
  </v:group><![endif]--><![if !vml]><img width=512 height=4
  src="template_arquivos/image002.gif" v:shapes="Group_x0020_4453 Shape_x0020_673"><![endif]><!--[if mso & !supportInlineShapes & supportFields]><v:shape
   id="_x0000_i1025" type="#_x0000_t75" style='width:381.75pt;height:.75pt'>
   <v:imagedata croptop="-65520f" cropbottom="65520f"/>
  </v:shape><span style='mso-element:field-end'></span><![endif]--></p>
  
  </div>
  
  </body>
  
  </html>
  `;
}

export default fullModelHtml;